baseURL = "https://cassiobotaro.dev/"
locale = "pt-br"
defaultContentLanguage = "pt-br"
title = "cassiobotaro"
theme = "hugo-coder"
pagination.pagerSize = 20
canonifyURLs = true
enableEmoji = true
enableGitInfo = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
author = "Cássio Botaro"
colorScheme = "dark"
avatarURL = "images/profile.png"
description = "Cássio Botaro's personal site and blog"
keywords = "python,go,developer,software,engineering"
info = "Software Developer Engineer"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/cassiobotaro/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/cassiobotaro/"

[[params.social]]
name = "YouTube"
icon = "fa-brands fa-youtube fa-2x"
weight = 2
url = "https://www.youtube.com/cassiobotaro"

[[params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 3
url = "/posts/index.xml"

[languages.pt-br]
label = "Português"
weight = 1

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Séries"
weight = 3
url = "series/"

[languages.en]
label = "English"
weight = 2

[languages.en.params]
info = "Software Developer Engineer"
description = "Cássio Botaro's articles in English"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[params.giscus]
  repo = "cassiobotaro/cassiobotaro.github.io"
  repoID = "R_kgDOMuDoQQ"
  category = "General"
  categoryID = "DIC_kwDOMuDoQc4C4UUD"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "pt"

[params.googleTagManager]
id = "G-WDYLFLXCKD"
